AWSTemplateFormatVersion: 2010-09-09
Description: Create SSM Parameter
Parameters:
  name:
    Type: String
  value:
    Type: String
Resources:
  BasicParameter:
    Type: 'AWS::SSM::Parameter'
    Properties:
      Name: !Ref name
      Type: String
      Value: !Ref value
      Description: parameter store entry
    Metadata:
      'AWS::CloudFormation::Designer':
        id: 10765060-f65c-42ca-916d-42f25f93b1f8


